version: '3'

services: 

# first container for hosting up our development server
  website:
    build: 
      #where we need all the files and images to be pulled from for this image
      context: .
      # location of the docker file to construct the image for this service
      dockerfile: Dockerfile.dev

      # - in yml defines the arrays
    ports: 
      - "3000:3000"
    volumes: 
      -  /app/node_modules
      - .:/app  
  
  #second container for rerunning all the test cases
  tests:
    build: 
     context: .
     dockerfile: Dockerfile.dev

    volumes:
     - /app/node_modules
     - . :/app

    command: ["npm", "start", "test"]

      